inputs:
  version:
    default: 0.0.0
    required: false
runs:
  steps:
    - name: Publish code coverage report
      uses: actions/upload-artifact@v4.3.1
      with:
        compression-level: 9
        if-no-files-found: warn
        name: coverage-$inputs.version
        overwrite: true
        path: .artifacts/coverage