inputs:
  shell:
    default: bash
    required: false
  workspace:
    default: $github.workspace
    required: false
runs:
  using: "composite"
  steps:
    - name: Artifacts version
      run: echo "artifacts_version=$(date + '%Y.%m.%d.%H%M')" >> $GITHUB_ENV
      shell: $inputs.shell
      working-directory: $inputs.workspace
    - name: Artifacts version (preview)
      run: echo "artifacts_version_preview=$(date + '%Y.%m.%d.preview-%H%M')" >> $GITHUB_ENV
      shell: $inputs.shell
      working-directory: $inputs.workspace
